backend:
  name: git-gateway
  branch: main
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Team Page'
        name: 'team'
        format: 'json'
        file: 'src/routes/team/data/team.json'
        fields:
          - { label: Title, name: title, widget: string }
          - label: 'Team Member'
            name: team-member
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image, optional: true }
media_folder: 'static/uploads'
public_folder: '/uploads'
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
