backend:
  name: git-gateway
  branch: main
collections:
  - label: Team
    name: team
    folder: src/routes/team/data
    widget: list
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Position, name: position, widget: string }
      - { label: Photo, name: photo, widget: image }
  - label: projects
    name: projects
    folder: src/routes/projects/data
    create: true
    fields:
      - name: name
      - name: location
      - name: slug
        widget: markdown
media_folder: 'static/uploads'
public_folder: '/uploads'
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
