backend:
  name: git-gateway
  branch: main
collections:
  - name: projects
    label: projects
    folder: src/routes/projects/data
    create: true
    fields:
      - name: name
      - name: location
      - name: slug
        widget: markdown

  - label: 'Team Members'
    name: 'team-members'
    format: json
    files:
      - label: 'Team Members Page'
        name: 'team'
        file: 'src/routes/team/data/team.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
media_folder: 'static/uploads'
public_folder: '/uploads'
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
