backend:
  name: git-gateway
  repo: ksmaineadmin/netechair
  branch: main
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Team Page'
        name: 'team'
        format: 'json'
        file: 'static/data/team.json'
        fields:
          - { label: Title, name: title, widget: string }
          - label: 'Team Member'
            name: teamMember
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image, required: false }
  - name: 'projects' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Projects' # Used in the UI
    label_singular: 'Project' # Used in the UI, ie: "New Post"
    create: true # Allow users to create new documents in this collection
    format: 'json'
    folder: 'static/data/projects'
    file: 'static/data/projects.json'
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Location', name: 'location', widget: 'string', tagname: 'h2' }
      # - label: 'Cover Image'
      #   name: 'image'
      #   widget: 'image'
      #   required: false
      #   tagname: ''
      - label: 'Images'
        label_singular: 'image'
        name: 'images'
        widget: 'list'
        collapsed: true
        summary: '{{fields.image}}'
        field: { label: Image, name: image, widget: image }
media_folder: 'static/uploads'
public_folder: '/uploads'
site_url: https://netechair.netlify.app
display_url: https://netechair.netlify.app
# logo_url: https://your-site.com/images/logo.svg
