backend:
  name: git-gateway
  repo: ksmaineadmin/netechair
  branch: main
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Team Page'
        name: 'team'
        format: 'json'
        file: 'static/data/team.json'
        fields:
          - { label: Title, name: title, widget: string }
          - label: 'Team Member'
            name: teamMember
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image, required: false }
  - label: 'Portfolio'
    name: 'portfolio'
    files:
      - label: 'Portfolio images'
        name: 'portfolioImages'
        file: 'static/data/projects.json'
        fields:
          - label: 'Images'
            label_singular: 'image'
            name: 'images'
            widget: 'list'
            collapsed: true
            summary: '{{fields.image}}'
            field: { label: Image, name: image, widget: image }

media_folder: 'static/uploads'
public_folder: '/uploads'
site_url: https://netechair.netlify.app
display_url: https://netechair.netlify.app
# logo_url: https://your-site.com/images/logo.svg
