backend:
  name: git-gateway
  branch: main
collections:
  - label: 'Blog'
    name: 'blog'
    file: 'src/routes/team/data/team.json'
    format: json
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
media_folder: 'static/uploads'
public_folder: '/uploads'
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
