backend:
  name: git-gateway
  branch: main
collections:
  - label: 'Testimonials'
    name: 'testimonials'
    collapsed: false
    widget: 'list'
    format: 'json'
    file: 'src/routes/team/data/team.json'
    folder: 'src/routes/projects/data'
    fields:
      - { label: Quote, name: quote, widget: string, default: 'Everything is awesome!' }
      - { label: Author, name: author, widget: string }
media_folder: 'static/uploads'
public_folder: '/uploads'
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
